name: generate-code

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 10 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: lrstanley/.github/composite/go-versions@master
        id: goversion
        with:
          version: latest
      - uses: lrstanley/.github/composite/install-go@master
        with:
          version: ${{ steps.goversion.outputs.version }}
      - uses: actions/checkout@v6
      - uses: lrstanley/.github/composite/invoke-task@master
        with:
          task: go-generate,generate
          allow-undefined: false
      - uses: EndBug/add-and-commit@7db2a1ad7f9311cb3da5c882bdb6cb70a6a95f99
        with:
          message: "chore(gen): codegen changes"
          commit: "--signoff"
          pathspec_error_handling: "ignore"
          add: "*.go"
