name: generate-code

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 10 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: install-go
        uses: actions/setup-go@v5
        with:
          go-version: latest
      - uses: actions/checkout@v4
      - run: make generate
      - uses: EndBug/add-and-commit@b66b3d957b9853122a0a71f4e5d5f5fa3f940e9a
        with:
          message: "chore(gen): codegen changes"
          commit: "--signoff"
          pathspec_error_handling: "ignore"
          add: "*.go"
