name: generate-code

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 10 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./codegen/generate.sh
      - uses: EndBug/add-and-commit@af39be11779239242ac2d3e47148221973246379
        with:
          message: "chore(gen): codegen changes"
          commit: "--signoff"
          pathspec_error_handling: "ignore"
          add: "*.go"
