name: generate-code

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 10 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./codegen/generate.sh
      - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b
        with:
          message: "chore(gen): codegen changes"
          commit: "--signoff"
          pathspec_error_handling: "ignore"
          add: "*.go"
